### PR TITLE
Expose kprobe's maxactive parameter in bcc

### LINKED ISSUE #1072: tools/tcpaccept.py's kretprobes not triggered due to low maxactive
When a kretprobe is installed on a kernel function, there is a maximum limit of how many calls in parallel it can catch (aka "maxactive"). In the case of a eBPF kretprobe, the maxactive is let to the default as defined in kernel/kprobes.c:

```
        /* Pre-allocate memory for max kretprobe instances */
        if (rp->maxactive <= 0) {
#ifdef CONFIG_PREEMPT
                rp->maxactive = max_t(unsigned int, 10, 2*num_possible_cpus());
#else
                rp->maxactive = num_possible_cpus();
#endif
        }
```

The maxactive can be as low as 1 on single-cores on kernel without CONFIG_PREEMPT.

tools/tcpaccept.py installs a kretprobe on `inet_csk_accept()` but that function can sleep for a long time (waiting for an incoming connection).

How to reproduce:

1. Start the tracer: `sudo ./tools/tcpaccept.py`
2. In another shell, start a bunch of processes waiting on the `accept()` system call: `for i in $(seq 1 25) ; do (busybox nc -l -p $((8081 + i)) &) ; done`
3. Start nginx locally: `sudo docker run -d nginx`
4. Connect to nginx: `curl 172.17.0.2`
5. Notice that there is no "accept" event

Note: use `nc` from `busybox` to reproduce this issue. `nc` from https://nmap.org/ncat (the default on Fedora) will not reproduce the issue because it does not block on the accept() system call (it waits on the `select()` system call to know when there is an incoming connection and only start the `accept()` system call at that time).

Similar issue also reported on https://github.com/weaveworks/tcptracer-bpf/issues/24 & https://github.com/weaveworks/tcptracer-bpf/issues/34

### PR DESCRIPTION
**Pull request by pchaigno**
When a kretprobe is installed on a kernel function, there is a limit on how many parallel calls it can catch. You can change that limit with the `maxactive` parameter. Since [commit `696ced4` ("tracing/kprobes: expose maxactive for kretprobe in kprobe_events")](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=696ced4fb1d76802f864d8848aa4716633f83c17) in the Linux kernel, debugfs exposes that parameter.

This pull request exposes that parameter in bcc as well, through `bpf_attach_kprobe` in libbcc and `BPF.attach_kretprobe` at the Python level. If a `maxactive` value is given, we fallback to using debugfs to install the kprobe event, instead of the usual `perf_event_open`.

For kernels without `maxactive` supports in debugfs, the error resolution is not straightforward. The kernel will still install a probe, but under a different name. We therefore need to check for our expected name, delete the probe with the different name, and try to attach the probe again, without the `maxactive` value.

Fixes #1072 #1250

/cc @alban @anisse

### CODE REVIEW

**Comment by abc123abd** [comment]
[buildbot, test this please]

**Comment by yonghong-song** [comment]
[buildbot, test this please]

File: src/cc/libbpf.c [hunk 1]
```diff
@@ -856,47 +856,100 @@ static int bpf_attach_tracing_event(int progfd, const char *event_path, int pid,
...
+      if (access(fname, F_OK) == -1) {
+        // Deleting kprobe event with incorrect name.
+        kfd = open("/sys/kernel/debug/tracing/kprobe_events",
+                   O_WRONLY | O_APPEND, 0);
+        if (kfd < 0) {
+          fprintf(stderr, "open(/sys/kernel/debug/tracing/kprobe_events): %s\n",
+                  strerror(errno));
+          return -1;
+        }
+        snprintf(fname, sizeof(fname), "-:kprobes/%s_0", ev_name);
```
Comment (yonghong-song) [inline src/cc/libbpf.c]: It took a while for me to understand why a different name is used here. I did not check the kernel, but looks like kernel is pretty consistent with this name regardless of what probe name you gave to the kernel.

Comment (pchaigno) [reply src/cc/libbpf.c]: Oh, right! I'll add a comment.

Comment (pchaigno) [reply src/cc/libbpf.c]: Uh. I didn't get time to add that comment... I guess it's in the commit message at least.

Comment (yonghong-song) [reply src/cc/libbpf.c]: it should be okay. It is in the comments as well.

File: src/cc/libbpf.c [hunk 2]
```diff
@@ -856,47 +856,100 @@ static int bpf_attach_tracing_event(int progfd, const char *event_path, int pid,
...
+
+  snprintf(ev_alias, sizeof(ev_alias), "%s_bcc_%d", ev_name, getpid());
+
+  if (fn_offset > 0 && attach_type == BPF_PROBE_ENTRY)
+    snprintf(buf, buf_size, "p:kprobes/%s %s+%"PRIu64,
+             ev_alias, fn_name, fn_offset);
+  else if (maxactive > 0 && attach_type == BPF_PROBE_RETURN)
+    snprintf(buf, buf_size, "r%d:kprobes/%s %s",
+             maxactive, ev_alias, fn_name);
+  else
```
Comment (palmtenor) [inline src/cc/libbpf.c]: Does `maxactive` do anything in k(entry)probe? If not, maybe we should check that the value should be 0?

File: src/cc/libbpf.c (hunk 1 above)
Comment (palmtenor) [inline src/cc/libbpf.c]: Is it possible to re-use detach kprobe logic here?

File: src/cc/libbpf.c [hunk 3]
```diff
@@ -856,47 +856,100 @@ static int bpf_attach_tracing_event(int progfd, const char *event_path, int pid,
...
+            fprintf(stderr, "cannot detach kprobe, probe entry may not exist\n");
+          else
+            fprintf(stderr, "cannot detach kprobe, %s\n", strerror(errno));
+          close(kfd);
+          goto error;
+        }
+        close(kfd);
+
+        // Re-creating kprobe event without maxactive.
+        if (create_kprobe_event(buf, ev_name, attach_type, fn_name,
```
Comment (palmtenor) [inline src/cc/libbpf.c]: So... ideally here we should go back and try use Perf Event based approach?

Comment (yonghong-song) [reply src/cc/libbpf.c]: probably not needed. pref event based approach is supported in 4.17 and maxactive is supported in 4.12...

File: src/cc/libbpf.c (hunk 2 above)
Comment (pchaigno) [reply src/cc/libbpf.c]: `maxactive` doesn't do anything for kprobes. Do you mean check that the value is 0 at the beginning of `bpf_attach_kprobe`?

File: src/cc/libbpf.c (hunk 1 above)
Comment (pchaigno) [reply src/cc/libbpf.c]: I considered it, but `bpf_detach_probe` also contains some code to handle the case where we attached the probe using `perf_event_open` (it iterates on the list of events). We could break `bpf_detach_probe` down to refactor, but I want to try and add support for `maxactive` in `perf_event_open`, so I thought I'd refactor after that.

File: src/cc/libbpf.c (hunk 3 above)
Comment (pchaigno) [reply src/cc/libbpf.c]: Hm. I missed that. I should've called `bpf_attach_kprobe` with `maxactive=0` instead. I could refactor if you think it's worth it.

Also, I might be missing something, but is there any reason the `perf_event_open` API is preferred to the debugfs'?

File: src/cc/libbpf.c (hunk 1 above)
Comment (yzhao1012) [reply src/cc/libbpf.c]: Sorry to bug a closed issue.

But where is the documentation for maxactive as referred in "See the kprobes documentation for its default value."?

We run into issue similar to https://github.com/iovisor/bcc/issues/1920 where bpf_trace_printk() states that the perf_submit() succeeded, but user-space did not read the events from the perf buffer.

Comment (pchaigno) [reply src/cc/libbpf.c]: The default value is discussed in [the kprobes documentation in the kernel](https://www.kernel.org/doc/Documentation/kprobes.txt):

> If maxactive <= 0, it is
set to a default value.  If CONFIG_PREEMPT is enabled, the default
is max(10, 2*NR_CPUS).  Otherwise, the default is NR_CPUS.
